### ISSUE TITLE
Precision Drill does not function

### ISSUE THREAD

**Issue by unknown41030** [WMF-Industries/ExpandedIndustries#15]
The precision drill does not function in game. It was provided with creative a water source. It appears that the liquid booster has been set to a 0x multiplier such that as soon as the drill has enough liquid to run, it immediately shuts off. The drill can sometimes produce 1 resource before it shuts off.

**Comment by WMF-Industries** [comment]
Fixed, please update the mod!
Thanks for reporting :)
