### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by Gab304** [WMF-Industries/ExpandedIndustries#16]
there are some problems with the Starium synthesizer and the Lumium Smelter. the amount of necessary materials indicated in the info are incorrect especially when upgraded with overdrive

**Comment by WMF-Industries** [comment]
Hi there! I don't really know how come hardcoded game values would be incorrect, could you send me a video of it or explain it in more detail? Also remember that overdrive boosts speed of all the buildings by 50, 125 or 150%, that means the buildings will produce faster, but they will also use more resources

**Comment by Gab304** [comment]
Yes i know, i've done the test in sandbox whit item source end the White
drills, i'll send you a video later
Il giorno sab 15 lug 2023 alle 11:29 WMF ***@***.***> ha
scritto:
