### ISSUE TITLE
lumium smelter desc 

### ISSUE THREAD

**Issue by JasperChaseTOQ** [WMF-Industries/ExpandedIndustries#17]
in the description of the lumium smelter it says it uses peridotium but it shows input as starium, im not sure which one is incorrect however considering they both show differing items im sure that at least one is incorrect (as in im not sure if its meant to be peridotium or starium)

![Screenshot 2023-07-19 225433](https://github.com/WMF-Industries/ExpandedIndustries/assets/103849596/085456fe-0073-46e6-9ce3-319065568210)

**Comment by WMF-Industries** [comment]
fixed the mistake in the newest build, thanks for reporting!
