### ISSUE TITLE
item description

### ISSUE THREAD

**Issue by JasperChaseTOQ** [WMF-Industries/ExpandedIndustries#18]
hello in https://github.com/WMF-Industries/ExpandedIndustries/blob/Mods/assets/bundles/bundle.properties
the descriptions for the items are missing and that renders the items to not show 
which mod its from which can become quite confusing when one has multiple mods installed

![20230805142834_1](https://github.com/WMF-Industries/ExpandedIndustries/assets/103849596/1bbb8b8e-548d-43de-983b-96b953970f78)
![20230805142818_1](https://github.com/WMF-Industries/ExpandedIndustries/assets/103849596/564fb357-34bd-4d08-b4c9-4ae917158ffc)
![20230805142733_1](https://github.com/WMF-Industries/ExpandedIndustries/assets/103849596/c4b0c80a-dea6-4159-8d2c-89cc4e8b43ca)
![20230805142812_1](https://github.com/WMF-Industries/ExpandedIndustries/assets/103849596/752e17ba-60e0-4e62-835e-b61cc26aa01b)

**Comment by WMF-Industries** [comment]
Item descriptions will be added in the next build, thanks for the reminder :)
