### ISSUE TITLE
error while loading into the game

### ISSUE THREAD

**Issue by Noxx67** [WMF-Industries/ExpandedIndustries#2]
this
![Screenshot_20211219-180320](https://user-images.githubusercontent.com/75849681/146683943-042c32fa-77e7-4260-9853-a9a18013ca90.png)
![Screenshot_20211219-180312](https://user-images.githubusercontent.com/75849681/146683937-2ac07864-9c49-41b8-89f2-bd8c4ea8959f.png)
![Screenshot_20211219-180316](https://user-images.githubusercontent.com/75849681/146683941-6333d8c7-1239-433a-a2a9-e8e93f31b7e7.png)

idk what am i missing.
the version i am in is v6 126.2

**Comment by WMF-Industries** [comment]
Hi! I am sorry that this happened to you, i have updated the mod, try updating it and tell me if the errors still exist. Sorry for that :c
