### ISSUE TITLE
unloaders

### ISSUE THREAD

**Issue by JasperChaseTOQ** [WMF-Industries/ExpandedIndustries#20]
unloaders do not require power however they connect to power nodes for some reason

**Comment by WMF-Industries** [comment]
Some unloaders are meant to conduct power, as stated in their description.

**Comment by JasperChaseTOQ** [comment]
my apologies it was only the advanced unloader, however the advanced unloader does connect, however it does not mention power in the description nor does it have a power bar
![20230805182445_1](https://github.com/WMF-Industries/ExpandedIndustries/assets/103849596/9fa1009e-157e-47a7-8c93-2eb8c8d22184)
![20230805182409_1](https://github.com/WMF-Industries/ExpandedIndustries/assets/103849596/a2d90fbc-b7b7-4de2-94a4-9bf61cf07e87)

**Comment by JasperChaseTOQ** [comment]
oh it shows conduct power nvm im blind as hell sorry
