### ISSUE TITLE
steam turbine

### ISSUE THREAD

**Issue by JasperChaseTOQ** [WMF-Industries/ExpandedIndustries#21]
the steam turbine requires the same amount of coal/spore pod/pyratite/etc as the steam generator, however it consumes it every 2.5 seconds vs the steam generators 1.5 seconds

in essence the steam turbine (the upgraded version of the steam generator) actually requires less input then the steam generator but produces significantly more power

**Comment by WMF-Industries** [comment]
Steam Turbine will get rebalanced in the future.
