### ISSUE TITLE
peridotium reactor

### ISSUE THREAD

**Issue by JasperChaseTOQ** [WMF-Industries/ExpandedIndustries#22]
regarding the peridotium reactor, it is the upgrade of the thorium reactor however unlike the thorium reactor which requires cryofluid as coolant, the peridotium uses water which is extremely cheaper.

also a small suggestion i have would be to add peridotium to the build cost or to change the starium cost to peridotium as to ensure people actually have peridotium to be able to build it

![20230805150440_1](https://github.com/WMF-Industries/ExpandedIndustries/assets/103849596/4e4ee9c5-e6e2-4ce0-97e9-d27071308c2c)
![20230805150510_1](https://github.com/WMF-Industries/ExpandedIndustries/assets/103849596/00924300-7ffc-48fc-b9f0-5dbebff1e594)

**Comment by WMF-Industries** [comment]
One cryofluid mixer can support 5 thorium reactors, one impulse pump can support only 1.5 peridotium reactors, seems balanced to me. You also have to remember that peridotium reactor takes more stuff to be build, uses richer fuel and has a bigger explosion that deals much more damage.
Regarding the suggestion about changing what's in the build cost, i won't do it, however i will add peridotium to the required research for the reactor.

**Comment by JasperChaseTOQ** [comment]
> One cryofluid mixer can support 5 thorium reactors, one impulse pump can support only 1.5 peridotium reactors, seems balanced to me. You also have to remember that peridotium reactor takes more stuff to be build, uses richer fuel and has a bigger explosion that deals much more damage. Regarding the suggestion about changing what's in the build cost, i won't do it, however i will add peridotium to the required research for the reactor.

i do agree with all your points there however its more the titanium part as some maps dont have titanium so that limits cyrofluid and therefore limits energy aspects of those maps while peridotium can be used in more maps (and while yes theres the argument of lauch pads cryofluid is a liquid so it cant be transfered plus thats not a very efficent supply method. 

adding that to the research works just as well thank you :)
