### ISSUE TITLE
Can't delete some buildings

### ISSUE THREAD

**Issue by SwiftNicholas** [WMF-Industries/ExpandedIndustries#6]
the starium refiner (that makes starium alloy) is not deletable.
There are a few buildings that are frog sprites, also not deletable
Starium Conveyors are not destroyable by the enemy (not sure if this is intentional)

**Comment by WMF-Industries** [comment]
Hey, sorry for late answer - i am remaking Expanded Industries in Java, these issues will be fixed in the first Java version
The hjson version of the mod is broken and not meant to be used anymore, it just wasn't ready for v7 changes so sorry about that
