### ISSUE TITLE
Please fix your mod

### ISSUE THREAD

**Issue by Borkie00** [WMF-Industries/ExpandedIndustries#7]
![Screenshot_Mindustry_2022-11-08-05-46-30-405](https://user-images.githubusercontent.com/117688645/200422882-542f11be-45f6-4db8-b532-ed32d37c5e70.png)

**Comment by WMF-Industries** [comment]
I am working on 1.5B3, will try to fix all the issues/bugs
However, i see no issues with the code, nor the mod in-game, could you please update your mod to the newest version or give me more details? (game version, mod version)
