### ISSUE TITLE
Hey what's up with the starium refiner and lumium smelter being in the eriker tech tree is that a bug

### ISSUE THREAD

**Issue by X99hammers** [WMF-Industries/ExpandedIndustries#8]
I was trying to get the starium alloy conveyer and noticed the refiner was in the eriker tech tree 
![Screenshot_20221125-003643](https://user-images.githubusercontent.com/119030104/203908413-d7a8ae09-ebf9-4d50-aae4-3179c111b1f2.png)

**Comment by WMF-Industries** [comment]
Will fix soon

**Comment by WMF-Industries** [comment]
That didn't happen to me yet, pretty weird, perhaps other mods are messing with it? Ima try to fix it somehow

**Comment by WMF-Industries** [comment]
figured out the issue, the bug is no longer present in the newest mod build
