### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by OOYYXX** [WMF-Industries/ExpandedIndustries#9]
no sight of precision drill , hammer drill and starium refiner in tech tree
![未命名](https://user-images.githubusercontent.com/119068146/204033622-a54cb283-740c-4f72-a721-c39f7707c6f5.png)

**Comment by WMF-Industries** [comment]
Right, must have missed them in the tree, gonna fix it

**Comment by WMF-Industries** [comment]
The bug has been successfully fixed and won't be present in the newest mod build
